community/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.views.generic.base import RedirectView
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('index/', views.home, name='index'),
    path('', RedirectView.as_view(url='index')),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('signup/', views.signup_view, name='register'),
    path('profile/', views.profile_final_view, name='profile_final'),
    path('profile/edit/', views.profile_final_edit_view, name='profile_edit_final'),
    path('contact/', views.contact_view, name='contact'),
    path('about/', views.about_view, name='about'),

    path('post/create/', views.PostCreateView.as_view(success_url='/community/post')),
    path('post/delete/<int:pk>',
         views.PostDeleteView.as_view(success_url='/community/post')),
    path('post/', views.PostListView.as_view()),
    path('activity/', views.AllPostListView.as_view()),

    path('group/', views.group_view, name='group'),
    path('group/details/', views.groupdetails_view, name='group_details'),
    path('group/create/', views.GroupCreateView.as_view(success_url='/community/group')),

    path('member/', views.ProfileListView.as_view()),
    path('member/<int:pk>', views.ProfileDetailView.as_view()),

    path('profile/follow/<int:pk>', views.follow_view, name="follow_view"),
    path('profile/unfollow/<int:pk>', views.unfollow_view, name="unfollow_view"),

    path('profile/like/<int:pk>', views.like_view, name="follow_view"),
    path('profile/unlike/<int:pk>', views.unlike_view, name="unfollow_view"),
]

sportvision/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.views.generic.base import RedirectView
from django.conf.urls.static import static
from . import settings
from community import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('community/', include('community.urls')),
    path('', RedirectView.as_view(url='community')),
    path('accounts/', include('allauth.urls')),

    path('password/change/',
         auth_views.PasswordChangeView.as_view(
             template_name='accounts/change-password.html'),
         name='password_change'),
    path('password/change/done/',
         auth_views.PasswordChangeDoneView.as_view(
             template_name='accounts/change-password-done.html'),
         name='password_change_done'),

    path('reset/password/',
         auth_views.PasswordResetView.as_view(
             template_name='accounts/password-reset.html'),
         name='password_reset'),
    path('reset/password/send/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='accounts/password-reset-message.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='accounts/password-reset-key.html'),
         name='password_reset_confirm'),
    path('reset/password_complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='accounts/password-reset-key-done.html'),
         name='password_reset_complete'),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

community/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from django.core.validators import MinValueValidator, RegexValidator
from django.conf import settings
User = settings.AUTH_USER_MODEL


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=CASCADE)
    name = models.CharField(max_length=100)
    status = models.CharField(max_length=20, default="single", choices=(
        ("single", "single"), ("married", "married"), ("widow", "widow")))
    gender = models.CharField(max_length=20, default="male", choices=(
        ("Male", "Male"), ("Female", "Female")))
    address = models.TextField(null=True, blank=True)
    your_facebook = models.CharField(max_length=100)
    your_bio = models.TextField(null=True, blank=True)
    age = models.IntegerField(default=18, validators=[MinValueValidator(18)])
    picture = models.ImageField(null=True, blank=True)

    def __str__(self):
        return "%s" % self.user

    class Meta:
        db_table = 'profile'

    def set_data(self, n, sta, gen, form_pic, y_fb, y_bio, a='default'):
        self.name = n
        self.status = sta
        self.gender = gen
        temp = self.picture
        self.picture = form_pic
        if self.picture == None:
            self.picture = temp
        self.your_facebook = y_fb
        self.your_bio = y_bio
        self.address = a
        self.save()
        return 'done'


class Contact(models.Model):
    user = models.ForeignKey(User, on_delete=CASCADE)
    f_name = models.CharField(max_length=25)
    l_name = models.CharField(max_length=25)
    email = models.EmailField(null=True, blank=True)
    mobile = models.CharField(max_length=10)
    msg = models.TextField(max_length=500)

    def __str__(self):
        return "%s" % self.user

    class Meta:
        db_table = 'contact'

    def set_data(self, f_name1, l_name1, email1, mobile1, msg1):
        self.f_name = f_name1
        self.l_name = l_name1
        self.email = email1
        self.mobile = mobile1
        self.msg = msg1
        self.save()
        return 'done'


class Category(models.Model):
    C_name = models.CharField(max_length=35)
    C_disc = models.CharField(max_length=200)

    def __str__(self):
        return "%s" % self.C_name


class Post(models.Model):
    upload_by = models.ForeignKey(
        Profile, null=True, blank=True, on_delete=CASCADE)
    pic = models.ImageField(null=True, blank=True)
    subject = models.CharField(max_length=25)
    msg = models.TextField(max_length=500)
    cr_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "%s" % self.subject

    class Meta:
        db_table = 'Post'

    def set_data(self, pic1, subject1, msg1, cr_date1):
        self.pic = pic1
        self.subject = subject1
        self.msg = msg1
        self.cr_date = cr_date1
        self.save()
        return 'done'


class Comments(models.Model):
    post = models.ForeignKey(Post, on_delete=CASCADE)
    comment_by = models.ForeignKey(Profile, on_delete=CASCADE)
    msg = models.TextField(max_length=500)
    pic = models.ImageField(null=True, blank=True)
    flag = models.CharField(max_length=20, null=True, blank=True, choices=(
        ("racist", "racist"), ("abbusing", "abbusing")))
    cr_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "%s" % self.msg

    class Meta:
        db_table = 'Comment'

    def set_data(self, pic1, subject1, msg1, cr_date1):
        self.pic = pic1
        self.subject = subject1
        self.msg = msg1
        self.cr_date = cr_date1
        self.save()
        return 'done'


class Like(models.Model):
    like_post = models.ForeignKey(Post, on_delete=CASCADE)
    like_by = models.ForeignKey(Profile, on_delete=CASCADE)
    cr_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "%s" % self.like_by

    class Meta:
        db_table = 'Like'


class Follow(models.Model):
    profile = models.ForeignKey(
        Profile, on_delete=CASCADE, related_name='profile')
    followed_by = models.ForeignKey(
        Profile, on_delete=CASCADE, related_name='followed_by')

    def __str__(self):
        return "%s" % self.followed_by

    class Meta:
        db_table = 'Follow'


class Community(models.Model):
    c_admin = models.ForeignKey(
        Profile, null=True, blank=True, on_delete=CASCADE)
    c_name = models.CharField(primary_key=True, max_length=60)
    visiblity = models.CharField(max_length=20, choices=(
        ("private", "private"), ("public", "public")))
    pic = models.ImageField(null=True, blank=True)
    desc = models.CharField(max_length=20)
    cr_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "%s" % self.c_name

    class Meta:
        db_table = 'Community'

    def set_data(self, pic1, subject1, msg1, cr_date1):
        self.pic = pic1
        self.subject = subject1
        self.msg = msg1
        self.cr_date = cr_date1
        self.save()
        return 'done'


class CommunityRule(models.Model):
    c_name = models.ForeignKey(Community, on_delete=CASCADE)
    title = models.CharField(max_length=20)
    desc = models.CharField(max_length=500)
    cr_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "%s" % self.c_name

    class Meta:
        db_table = 'CommunityRule'

    def set_data(self, pic1, subject1, msg1, cr_date1):
        self.pic = pic1
        self.subject = subject1
        self.msg = msg1
        self.cr_date = cr_date1
        self.save()
        return 'done'

community/forms.py
import profile

from django import forms
from django.contrib.auth import get_user_model
from allauth.account.forms import SignupForm
from community.models import Profile, Category, Contact


class RegistrationForm(SignupForm):
    class Meta():
        model = get_user_model()
        fields = ('username', 'email', 'password1', 'password2')

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.fields['username'].label = 'Display Name'
            self.fields['Email'].label = "Email Address"


class ProfileForm(forms.ModelForm):
    class Meta():
        model = Profile

        fields = ['picture', 'id']

        labels = {'picture': ''}


class CategoryForm(forms.ModelForm):
    class Meta():
        model = Category
        fields = "__all__"

templates/community/Group_Create.html
{% extends 'community/master.html' %}
{% load static %}
{% block head %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Profile</title>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
    <link rel="stylesheet" href="{% static '/css/style_index_final.css' %}">
    <link rel="stylesheet" href="{% static '/css/profile_final.css' %}">
    <style>

        .my-class{
            display: flex !important;
            flex-direction: column !important;
            justify-content: center !important;
            align-items: center;
        }

        .my-btns{
            display: flex;
            justify-content: space-between;
            width: 100%;
        }
       .edit-profilee{
           display: flex;
           justify-content: center;
       }
       .edit-profilee img{
             max-width: 300px !important;
            max-height: 300px !important;
            width: 300px !important;
            height: 300px !important;
            border-radius: 0 !important;
            position: relative !important;
            object-fit: cover;
       }
   </style>
</head>
{% endblock %}

{% block container %}
<body>
<div class="main-content edit-content">
    <div class="col-xl-8 order-xl-1">
        <div class="card bg-secondary shadow">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="card-header bg-white border-0">
                    <div class="my-class">
                        <div class="my-btns">
                            <div class="">
                                <a href="/community/index" class="btn btn-sm btn-primary">Cancel</a>
                            </div>
                            <div class="">
                                <tr>
                                    <th><label for="id_pic"></label></th>
                                    <td><input type="file" name="pic" accept="image/*" id="id_pic"></td>
                                </tr>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <hr class="my-4">
                    <!-- Description -->
                    <h6 class="heading-small text-muted mb-4 pl-lg-4">Description</h6>
                    <div class="pl-lg-4">
                        <div class="form-group focused">
                            <label>Community Name</label>
                            <tr>
                                <th><label for="id_c_name"></label></th>
                                <td><input type="text" name="c_name"  maxlength="25" required id="id_c_name"></td>
                            </tr>
                        </div>
                        <div class="form-group focused">
                            <label>Community Description</label>
                            <tr>
                                <th><label for="id_desc"></label></th>
                                <td><input type="text" name="desc" cols="40" rows="4" maxlength="500" required id="id_desc" ></td>
                            </tr>
                        </div>
                        <div class="form-group focused">
                            <label>Visiblity</label>
                            <tr>
                               <th> <label for="id_visiblity"></label></th>
                                <td> <select name="visiblity" required id="id_visiblity">
                            <option value="">---------</option>
                            <option value="private" selected>private</option>
                            <option value="public">public</option>
                            </select></td>
                            </tr>
                        </div>
                        <div class="col-12 text-center">
                            <input type="submit" name="submit" value="Create" class="btn btn-sm btn-info mr-8">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
</div>
</div>
</body>
{% endblock %}

templates/community/activity.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Sports Communtiy</title>
  <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
  <link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.5.0/font/bootstrap-icons.min.css">
  <link rel="stylesheet" href="{% static '/css/style_index_final.css' %}">
<link rel="stylesheet" href="{% static 'css/activity.css' %}">
</head>
<!-- ======= Header ======= -->
<header id="header" class="fixed-top d-flex align-items-center">
  <div class="container d-flex align-items-center justify-content-between">

    <div class="logo">
      <h1 class="text-light"><a href="/community/index"><span>SportVision</span></a></h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
    </div>

    <nav id="navbar" class="navbar">
      <ul>
        <li><a class="nav-link scrollto active" href="/community/index">Home</a></li>
        <li class="dropdown"><a href="/community/index"><span>Community</span> <i class="bi bi-chevron-down"></i></a>
          <ul>
            <li><a href="/community/activity">Activity</a></li>
            <li><a href="/community/member">Members</a></li>
            <li><a href="#">Community</a></li>
          </ul>
        </li>
        <li><a class="nav-link scrollto" href="/community/about">About Us</a></li>
<!--        <li><a class="nav-link scrollto" href="/community/activity">Activity</a></li>-->

        <li><a class="nav-link scrollto" href="/community/contact">Contact</a></li>
        {% if user.is_authenticated %}


        <li><a class="getstarted signUp scrollto" href="/community/activity">Activity</a></li>
        <li><a class="getstarted signUp scrollto" href="/community/post/">MyPost</a></li>
        <li><a class="getstarted signUp scrollto" href="/community/post/create">CreatePost</a></li>
         <li><a class="getstarted signUp scrollto" href="/community/profile/">Profile</a></li>
        <li><a class="getstarted signUp scrollto" href="/community/logout">Logout</a></li>
        {% else %}
        <li><a class="getstarted signUp scrollto" href="/community/login">Log In</a></li>
        <li><a class="getstarted logIn scrollto" href="/community/signup">Sign Up</a></li>
        {% endif %}
      </ul>
      <i class="bi bi-list mobile-nav-toggle"></i>
    </nav><!-- .navbar -->

  </div>
</header><!-- End Header -->

<body>
<div class="main" style="margin:8rem">
    <section class="main-section">
        <section class="sectionPart">
            <section class="newsfeed">
                <form>
                        <input value="{{ request.GET.si }}" type="text" name="si" />
                        <input type="submit" value="Search" />
                    </form>
                <div class="newsfeed-section">

                    <!-- POST START HERE -->
                    <section class="post">
                         {% for p1 in post_list %}
                        <div class="content-header">
                            <div class="name">
                                <h3>{{user}}</h3>
                                <h5>{{p1.subject}}</h5>
                            </div>
                            <div class="more">
                                <a href="/community/post/delete/{{p1.id}}" ><span>delete</span></a>
                            </div>
                        </div>
                        <div class="img-section">
                            {% if p1.pic %}
                            <img src="{{p1.pic.url}}" alt="not found">
                            {% endif %}
                        </div>
                        <div class="desc-content">
                            <p class="para">{{p1.msg}}</p>
                        </div>
                        <div class="post-section">
                            <div class="icons-newsfeed">
                                <a href="/community/profile/like/{{p1.id}}">
                                    <span class="like"><svg aria-label="Like" class="_8-yf5 " fill="#262626" height="24"
                                                            viewBox="0 0 48 48" width="24">
                                            <path
                                                    d="M34.6 6.1c5.7 0 10.4 5.2 10.4 11.5 0 6.8-5.9 11-11.5 16S25 41.3 24 41.9c-1.1-.7-4.7-4-9.5-8.3-5.7-5-11.5-9.2-11.5-16C3 11.3 7.7 6.1 13.4 6.1c4.2 0 6.5 2 8.1 4.3 1.9 2.6 2.2 3.9 2.5 3.9.3 0 .6-1.3 2.5-3.9 1.6-2.3 3.9-4.3 8.1-4.3m0-3c-4.5 0-7.9 1.8-10.6 5.6-2.7-3.7-6.1-5.5-10.6-5.5C6 3.1 0 9.6 0 17.6c0 7.3 5.4 12 10.6 16.5.6.5 1.3 1.1 1.9 1.7l2.3 2c4.4 3.9 6.6 5.9 7.6 6.5.5.3 1.1.5 1.6.5.6 0 1.1-.2 1.6-.5 1-.6 2.8-2.2 7.8-6.8l2-1.8c.7-.6 1.3-1.2 2-1.7C42.7 29.6 48 25 48 17.6c0-8-6-14.5-13.4-14.5z">
                                            </path>
                                        </svg></span>
                                    </a>
<!--                                <span class="comment"><svg aria-label="Comment" class="_8-yf5 " fill="#262626"-->
<!--                                                           height="24" viewBox="0 0 48 48" width="24">-->
<!--                                            <path clip-rule="evenodd"-->
<!--                                                  d="M47.5 46.1l-2.8-11c1.8-3.3 2.8-7.1 2.8-11.1C47.5 11 37 .5 24 .5S.5 11 .5 24 11 47.5 24 47.5c4 0 7.8-1 11.1-2.8l11 2.8c.8.2 1.6-.6 1.4-1.4zm-3-22.1c0 4-1 7-2.6 10-.2.4-.3.9-.2 1.4l2.1 8.4-8.3-2.1c-.5-.1-1-.1-1.4.2-1.8 1-5.2 2.6-10 2.6-11.4 0-20.6-9.2-20.6-20.5S12.7 3.5 24 3.5 44.5 12.7 44.5 24z"-->
<!--                                                  fill-rule="evenodd"></path>-->
<!--                                        </svg></span>-->
<!--                                <span class="share"><svg aria-label="Share Post" class="_8-yf5 " fill="#262626"-->
<!--                                                         height="24" viewBox="0 0 48 48" width="24">-->
<!--                                            <path-->
<!--                                                    d="M47.8 3.8c-.3-.5-.8-.8-1.3-.8h-45C.9 3.1.3 3.5.1 4S0 5.2.4 5.7l15.9 15.6 5.5 22.6c.1.6.6 1 1.2 1.1h.2c.5 0 1-.3 1.3-.7l23.2-39c.4-.4.4-1 .1-1.5zM5.2 6.1h35.5L18 18.7 5.2 6.1zm18.7 33.6l-4.4-18.4L42.4 8.6 23.9 39.7z">-->
<!--                                            </path>-->
<!--                                        </svg></span>-->
<!--                                <span class="save"><svg aria-label="Save" class="_8-yf5 " fill="#262626" height="24"-->
<!--                                                        viewBox="0 0 48 48" width="24">-->
<!--                                            <path-->
<!--                                                    d="M43.5 48c-.4 0-.8-.2-1.1-.4L24 29 5.6 47.6c-.4.4-1.1.6-1.6.3-.6-.2-1-.8-1-1.4v-45C3 .7 3.7 0 4.5 0h39c.8 0 1.5.7 1.5 1.5v45c0 .6-.4 1.2-.9 1.4-.2.1-.4.1-.6.1zM24 26c.8 0 1.6.3 2.2.9l15.8 16V3H6v39.9l15.8-16c.6-.6 1.4-.9 2.2-.9z">-->
<!--                                            </path>-->
<!--                                        </svg></span>-->
                            </div>
                            <div class="desc">
                                <div class="likes">
                                    <span><strong>5 likes</strong></span>
                                </div>
                                <div class="comments">
                                    <div class="all-comments">
                                        <div class="single-comment">
                                            <h3>azamir seth</h3>
                                            <p class="para">nice</p>
                                            <span class="like-emoji"><svg aria-label="Like" class="_8-yf5 "
                                                                          fill="#262626" height="12" viewBox="0 0 48 48" width="12">
                                                        <path
                                                                d="M34.6 6.1c5.7 0 10.4 5.2 10.4 11.5 0 6.8-5.9 11-11.5 16S25 41.3 24 41.9c-1.1-.7-4.7-4-9.5-8.3-5.7-5-11.5-9.2-11.5-16C3 11.3 7.7 6.1 13.4 6.1c4.2 0 6.5 2 8.1 4.3 1.9 2.6 2.2 3.9 2.5 3.9.3 0 .6-1.3 2.5-3.9 1.6-2.3 3.9-4.3 8.1-4.3m0-3c-4.5 0-7.9 1.8-10.6 5.6-2.7-3.7-6.1-5.5-10.6-5.5C6 3.1 0 9.6 0 17.6c0 7.3 5.4 12 10.6 16.5.6.5 1.3 1.1 1.9 1.7l2.3 2c4.4 3.9 6.6 5.9 7.6 6.5.5.3 1.1.5 1.6.5.6 0 1.1-.2 1.6-.5 1-.6 2.8-2.2 7.8-6.8l2-1.8c.7-.6 1.3-1.2 2-1.7C42.7 29.6 48 25 48 17.6c0-8-6-14.5-13.4-14.5z">
                                                        </path>
                                                    </svg></span>
                                        </div>
                                        <div class="single-comment">
                                            <h3>battus</h3>
                                            <p class="para">awosom</p>
                                            <span class="like-emoji"><svg aria-label="Like" class="_8-yf5 "
                                                                          fill="#262626" height="12" viewBox="0 0 48 48" width="12">
                                                        <path
                                                                d="M34.6 6.1c5.7 0 10.4 5.2 10.4 11.5 0 6.8-5.9 11-11.5 16S25 41.3 24 41.9c-1.1-.7-4.7-4-9.5-8.3-5.7-5-11.5-9.2-11.5-16C3 11.3 7.7 6.1 13.4 6.1c4.2 0 6.5 2 8.1 4.3 1.9 2.6 2.2 3.9 2.5 3.9.3 0 .6-1.3 2.5-3.9 1.6-2.3 3.9-4.3 8.1-4.3m0-3c-4.5 0-7.9 1.8-10.6 5.6-2.7-3.7-6.1-5.5-10.6-5.5C6 3.1 0 9.6 0 17.6c0 7.3 5.4 12 10.6 16.5.6.5 1.3 1.1 1.9 1.7l2.3 2c4.4 3.9 6.6 5.9 7.6 6.5.5.3 1.1.5 1.6.5.6 0 1.1-.2 1.6-.5 1-.6 2.8-2.2 7.8-6.8l2-1.8c.7-.6 1.3-1.2 2-1.7C42.7 29.6 48 25 48 17.6c0-8-6-14.5-13.4-14.5z">
                                                        </path>
                                                    </svg></span>
                                        </div>
                                    </div>
                                    <span class="clr">View all 2 comments</span>
                                    <div class="time-ago">
<!--                                        <span>12 HOURS AGO</span>-->
                                    </div>
                                    <div class="line"></div>
                                    <form action="" class="user-comment-section">
                                        <input type="text" name="" id="addComment" required
                                               placeholder="Add a comment...">
                                        <div class="toLeft">
                                            <button class="btn" type="submit"><span
                                                    class="post-btn">Post</span></button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </section>
                    <!-- POST ENDS HERE -->

                </div>
            </section>
        </section>
    </section>
</div>
</body>

<script src="https://unpkg.com/isotope-layout@3/dist/isotope.pkgd.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
<script src="{% static '/js/app.js' %}"></script>

</html>

templates/community/post_final.html
{% extends 'community/master.html' %}
{% load static %}
{% block head %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Profile</title>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
    <link rel="stylesheet" href="{% static '/css/style_index_final.css' %}">
   <link rel="stylesheet" href="{% static '/css/profile_final.css' %}">
   <style>

        .my-class{
            display: flex !important;
            flex-direction: column !important;
            justify-content: center !important;
            align-items: center;
        }

        .my-btns{
            display: flex;
            justify-content: space-between;
            width: 100%;
        }
       .edit-profilee{
           display: flex;
           justify-content: center;
       }
       .edit-profilee img{
             max-width: 300px !important;
            max-height: 300px !important;
            width: 300px !important;
            height: 300px !important;
            border-radius: 0 !important;
            position: relative !important;
            object-fit: cover;
       }
   </style>
</head>
{% endblock %}

{% block container %}
<body>
  <div class="main-content edit-content">
        <div class="col-xl-8 order-xl-1">
            <div class="card bg-secondary shadow">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="card-header bg-white border-0">
                        <div class="my-class">
                            <div class="my-btns">
                                <div class="">
                                    <a href="/community/index" class="btn btn-sm btn-primary">Cancel</a>
                                </div>
                                <div class="">
                                <tr>
                                    <th><label for="id_pic"></label></th>
                                    <td><input type="file" name="pic" accept="image/*" id="id_pic"></td>
                                </tr>
                                </div>
                            </div>
<!--                            <div class="edit-profilee col-4 ">-->
<!--                                <a href="">-->
<!--                                    <img src="" class="rounded-circle mt-4">-->
<!--                                </a>-->
<!--                            </div>-->
                        </div>
                    </div>
                    <div class="card-body">
                        <hr class="my-4">
                        <!-- Description -->
                        <h6 class="heading-small text-muted mb-4 pl-lg-4">Description</h6>
                        <div class="pl-lg-4">
                            <div class="form-group focused">
                                <label>Post Heading</label>
                                <tr>
                                    <th><label for="id_subject"></label></th>
                                    <td><input type="text" name="subject"  maxlength="25" required id="id_subject"></td>
                                </tr>
                            </div>
                            <div class="form-group focused">
                                <label>Post Description</label>
                                <tr>
                                    <th><label for="id_msg"></label></th>
                                    <td><textarea name="msg" cols="40" rows="4" maxlength="500" required id="id_msg" class="form-control form-control-alternative"></textarea></td>
                                </tr>
                            </div>

                            <div class="col-12 text-center">
                                <input type="submit" name="submit" value="Post" class="btn btn-sm btn-info mr-8">
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
      </div>
    </div>
  </div>
  
</body>
{% endblock %}